# Generated by Django 4.2.5 on 2023-11-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('serial', models.CharField(max_length=50)),
                ('fecha_mtto', models.DateField()),
                ('fecha_calibracion', models.DateField()),
                ('voltaje', models.CharField(max_length=50)),
                ('corriente_compresor', models.CharField(max_length=50)),
                ('corriente_motor', models.CharField(max_length=50)),
                ('Cliente', models.CharField(max_length=50)),
            ],
        ),
    ]
