# Generated by Django 4.2.6 on 2023-11-29 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcrearempresa', '0002_empresas_nit'),
        ('webcrearequipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='equipo',
            name='empresa',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='webcrearempresa.empresas'),
            preserve_default=False,
        ),
    ]
