# Generated by Django 4.2.6 on 2023-12-05 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webregistro', '0004_alter_personas_numerocedula_alter_personas_telefono'),
        ('webcrearequipos', '0002_remove_equipo_cliente_equipo_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_creacion', models.DateField()),
                ('observacion', models.CharField(max_length=50)),
                ('voltage', models.CharField(max_length=50)),
                ('corriente_compresor', models.CharField(max_length=50)),
                ('corriente_motor', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcrearequipos.equipo')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webregistro.supervisores')),
                ('tecnicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webregistro.tecnicos')),
            ],
        ),
    ]
