# Generated by Django 4.2.6 on 2023-10-30 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webcrearempresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('PersonaID', models.AutoField(primary_key=True, serialize=False)),
                ('PrimerNombre', models.CharField(max_length=50)),
                ('SegundoNombre', models.CharField(max_length=50)),
                ('PrimerApellido', models.CharField(max_length=50)),
                ('SegundoApellido', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=255)),
                ('Telefono', models.CharField(max_length=20)),
                ('FechaNacimiento', models.DateField()),
                ('FechaCreacion', models.DateTimeField()),
                ('FechaModificacion', models.DateTimeField()),
                ('Email', models.CharField(max_length=50)),
                ('NumeroCedula', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('UsuarioID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreUsuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=255)),
                ('PersonaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webregistro.personas', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnicos',
            fields=[
                ('TecnicoID', models.AutoField(primary_key=True, serialize=False)),
                ('PersonaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webregistro.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisores',
            fields=[
                ('SupervisorID', models.AutoField(primary_key=True, serialize=False)),
                ('PersonaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webregistro.personas')),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ClienteID', models.AutoField(primary_key=True, serialize=False)),
                ('EmpresaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcrearempresa.empresas')),
                ('PersonaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webregistro.personas')),
            ],
        ),
    ]
