# Generated by Django 4.2.5 on 2023-10-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webregistro', '0003_alter_personas_email_alter_personas_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='NumeroCedula',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='Telefono',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
