# Generated by Django 4.2.6 on 2023-10-30 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('EmpresaID', models.AutoField(primary_key=True, serialize=False)),
                ('NombreEmpresa', models.CharField(max_length=255)),
                ('DireccionEmpresa', models.CharField(max_length=255)),
                ('FechaCreacion', models.DateTimeField()),
                ('FechaModificacion', models.DateTimeField()),
            ],
        ),
    ]
