# Generated by Django 4.2.6 on 2023-10-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrearempresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='nit',
            field=models.CharField(default='nit', max_length=255),
            preserve_default=False,
        ),
    ]
