# Generated by Django 4.2.6 on 2023-12-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcrearempresa', '0002_empresas_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='telefono',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
    ]
