# Generated by Django 4.2.5 on 2023-10-31 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webregistro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='Tipousuario',
            field=models.CharField(default='cliente', max_length=20),
            preserve_default=False,
        ),
    ]
