# Generated by Django 4.2.5 on 2023-10-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webregistro', '0002_personas_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personas',
            name='Email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='FechaCreacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personas',
            name='FechaModificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
